### ISSUE TITLE
Convert Data on Unit Change

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#112]
Need to convert energy usage and heat capacity data when units are changed for the facility

**Comment by rmroot** [comment]
Not converting in facility settings page.

Have added functionality to change units in a meter and warnings when units do not match facility settings

Converting energy use data when data is entered as total consumption when units change in meter

connects #381

**Comment by koay9f** [comment]
I think this is working out pretty well. If you change units in facility settings, it changes Monthly Meter Data and onward, which is good.
It doesn't change the meter heat capacity or Utilities "Total Energy" values. 
This could be a problem is someone messes up (entering data before realizing that they need to set their units on the settings page)
Since this does work, they could just look up the heat capacity in the units that it is locked to, and everything would work out fine. but might be nice to make a new issue to brainstorm how to change it?
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3305ba7a-5efe-4d49-b1f0-ee505fe991a0)

For now, (unless you have great ideas about above) maybe add the following warning text with the Collection units change text:
Heat Capacity's energy unit is set to the Energy Unit definined in the Facility settings when the meter was created. This cannot be changed. Utility energy data will be in this unit as well. Energy data in "Monthly Meter Data" will reflect the current Energy Unit and can be changed. 

Maybe talk about this tomorrow?

**Comment by rmroot** [comment]
Add energy unit dropdown for energy meters.
Move units to second row, site to source to first
Heat capacity and emissions on third
