### ISSUE TITLE
Update emissions factors to be CO2, ME, N2O

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1364]

**Comment by rmroot** [comment]
Added ability to create custom fuels and broke up existing fuel compositions. Still missing the following compositions from the GHG Emissions Factors PDF:

- Butane (Gas)
- Isobutane (Gas)
- Distillate Fuel Oil (Liquid)
- Residual Fuel Oil (Liquid)
- Heating Oil (Liquid)
- Pentane (Liquid)
- Biomass (Solid)
- Black Liquor (Solid)

Heating Oil, Biomass and Black Liquor are not in the PDF. Other values calculations don't match up with current emissions rates we have.

**Comment by koay9f** [comment]
Butane (Gas) - the emissions factors / MMBTU will be the same as liquid
Isobutane (Gas)- the emissions factors / MMBTU will be the same as liquid
Distillate Fuel Oil (Liquid) - this is the average of 1, 2, 4: CO2: 74.1, CH4: 3.0, N2O: 0.6
Residual Fuel Oil (Liquid) - this is the average of 5 & 6: CO2: 74.0, CH4: 3.0, N2O: 0.6
Heating Oil (Liquid) - this is the same as distillate fuel oil
Pentane (Liquid)- the emissions factors / MMBTU will be the same as liquid (maybe listed as "Pentanes Plus"\

Need to check with someone about these...
Biomass (Solid) - may decide to break this out into multiple fuels instead of generic "biomass (solid)"
Black Liquor (Solid) - this should probably be a LIQUID.
