### ISSUE TITLE
Add Settings link for corporate under switch menu

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#270]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8e2e35bd-2ad7-45db-9885-821704803a4c)

**Comment by koay9f** [comment]
Maybe also add the gear icon to the left menu?  I think at first we figured we wouldn't have to go back there a lot, but it turns out we are, at least in setup...

**Comment by cranfillkd** [comment]
I can add this but I think its confusing. All the other gears in this menu take you to a facility setting page.

The corporate menu page is right next to it.. Would you rather have the gear icon here instead of the ">"?

 ![Screen Shot 2021-04-26 at 2.06.56 PM.png](https://images.zenhubusercontent.com/5e00ded53da7a2493c3ff38c/89d85337-6cdc-476b-8adc-a4d319b8772e)

**Comment by koay9f** [comment]
If we switch "All facilities" to "Corporate Overview" I don't think it would be confusing.  Basically then that drop menu takes you to settings pages.  
What I know, is every time I tried to go to the corporate settings page, that is the menu I clicked on first.

A gear where you suggested might not be bad either.  I'm okay with multiple ways to get to the same place if they don't somehow conflict with each other.
