### ISSUE TITLE
Help Text Panel: Facility Management

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#448]
Fill out help text panel for facility management (settings) page (facility-help component)

**Comment by rmroot** [comment]
this issue taken care of in 

https://github.com/ORNL-AMO/VERIFI/pull/1118

same as account. balance help text for everything and having too much in the panel. open to suggestions

**Comment by koay9f** [comment]
Replace this:
Units are used for the data inputs and display in this facility. Data will be converted to the account settings when rolled up.

With this:
The Result Energy Unit determines the unit all your energy data is reported in. This can be changed here, at any time, to change the results in your Utility Data, Overview, and Data Visualization.  You can set your result unit in analysis independently and this will not change any analyses or reports. 
The Default Units only set the unit a new meter starts with. This can be set for each meter during meter setup. The Volume and Mass units are only used for setting the physical units of meters.

Change this:
 The Zip will be used to set the "Electricity Global Warming Potential", unless otherwise specified. This value is used to calculate the emissions for electricity meters in this facility.

To this:
Your zip code is used to set the "Electricity Global Warming Potential", unless otherwise specified. This value is used to calculate the emissions for electricity meters in this facility. If you do not see this field, set your country to "United States of America (the)".
