### ISSUE TITLE
Analysis Items - Edit/Pencil Button

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#644]
Will do the same thing as clicking the name, but we have all three elsewhere

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/62f9052f-c94d-47a4-8f8d-94eb89f0b855)

**Comment by rmroot** [comment]
We don't have all three anywhere. The pencil is in the utility data section because the entry's are edited with a pop up.

 Can add pencil here but then we probably want to add to reports?

Meters, meter readings, analysis groups and predictors do not have copy but have pencil/trash that trigger popups

**Comment by rmroot** [comment]
Lists for meters, reports and analysis have all 3 (edit, copy, delete) buttons

Meter readings and Predictors just have edit and delete. Didn't think copy made sense but can add if necessary

**Comment by koay9f** [comment]
agreed.  looks good
