### ISSUE TITLE
Updated Site To Source and Emissions Multipliers

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#667]
The agreement type will provide defaults for the checkboxes & site to source default value, though they can be changed by the user. The agreement type and check boxes will determine if a meter's numbers get added to the energy use and what multiplers are used for emissions calculations.

![image.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/8cd5337e-254e-4661-a4d8-fd5f7b3c435b)

**Comment by koay9f** [comment]
Edit - was dumb
Honestly, if "Include in Energy" = No, then there is not site-to-source multipler to use. so if htat is the case, should probably set to 1 (so math doesn't get mad) and hide it.
We probably need to rearrange the page a bit since the agreement type is editing the s2s field, but I think thats going to take more thought than a Friday afternoon, so I'll get back to you

**Comment by koay9f** [comment]
looks like it works, but only if you switch it after it has been set.
If you just make a new meter, and switch it to RECS or VPPA (or something with "Include in Energy" = False as a default) then it is still there
[Uploading... image.png]
